ignoreWorkspaceRootCheck: true
shellEmulator: true

packages:
  - playground
  - docs
  - packages/*
  - examples/*
  - desktop
  - packages/assets/*

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - electron
